{{- if ne .chezmoi.os "windows" -}}
[".local/share/zsh/plugins/powerlevel10k"]
    type = "git-repo"
    url = "https://github.com/romkatv/powerlevel10k.git"
    refreshPeriod = "168h"
    clone.args = ["--depth", "1"]

[".local/share/zsh/plugins/enhancd"]
    type = "git-repo"
    url = "https://github.com/b4b4r07/enhancd.git"
    refreshPeriod = "168h"
    clone.args = ["--depth", "1"]

[".local/share/zsh/plugins/fast-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zdharma-continuum/fast-syntax-highlighting.git"
    refreshPeriod = "168h"
    clone.args = ["--depth", "1"]

[".local/share/zsh/plugins/zsh-autosuggestions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-autosuggestions.git"
    refreshPeriod = "168h"
    clone.args = ["--depth", "1"]

[".local/share/aquaproj-aqua/bin/aqua"]
    type = "file"
    url = "https://github.com/aquaproj/aqua/releases/latest/download/aqua_{{ .chezmoi.os }}_{{ .chezmoi.arch }}.tar.gz"
    executable = true
    refreshPeriod = "168h"
    [".local/share/aquaproj-aqua/bin/aqua".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "aqua"]

[".local/share/nvim/lazy/lazy.nvim"]
    type = "git-repo"
    url = "https://github.com/folke/lazy.nvim.git"
    clone.args = ["--filter", "blob:none", "--branch", "stable"]
    pull.args = ["origin", "main"]
{{- end -}}
