{{- if ne .chezmoi.os "windows" -}}
[".local/share/aquaproj-aqua/bin/aqua"]
    type = "file"
    url = "https://github.com/aquaproj/aqua/releases/latest/download/aqua_{{ .chezmoi.os }}_{{ .chezmoi.arch }}.tar.gz"
    executable = true
    refreshPeriod = "168h"
    [".local/share/aquaproj-aqua/bin/aqua".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "aqua"]

[".local/share/nvim/lazy/lazy.nvim"]
    type = "git-repo"
    url = "https://github.com/folke/lazy.nvim.git"
    clone.args = ["--filter", "blob:none", "--branch", "stable"]

[".local/share/zinit/zinit.git"]
    type = "git-repo"
    url = "https://github.com/zdharma-continuum/zinit.git"
    clone.args = ["--depth", "1"]
{{- end -}}
