tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "sanemat/font"
brew "ansible"
brew "anyenv"
brew "coreutils"
brew "ghq"
brew "git"
brew "hub"
brew "kubectx"
brew "mas"
brew "neovim"
brew "sshrc"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "wakeonlan"
brew "wget"
brew "zsh"
brew "sanemat/font/ricty", args: ["with-powerline"]
cask "1password"
cask "alfred"
cask "appcleaner"
cask "bettertouchtool"
cask "clipy"
cask "docker"
cask "google-chrome-canary"
cask "google-japanese-ime"
cask "iterm2"
cask "karabiner-elements"
cask "onyx"
cask "vagrant"
cask "virtualbox"
cask "virtualbox-extension-pack"
cask "visual-studio-code"
mas "LINE", id: 539883307
mas "Microsoft Remote Desktop", id: 1295203466
mas "Spark", id: 1176895641
