---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
- type: standard
  ref: v2.2.0 # renovate: depName=aquaproj/aqua-registry

packages:
- name: BurntSushi/ripgrep@13.0.0
- name: cli/cli@v2.7.0
- name: junegunn/fzf@0.30.0
- name: neovim/neovim@v0.6.1
- name: ogham/exa@v0.10.1
- name: sharkdp/bat@v0.20.0
- name: stedolan/jq@jq-1.6
- name: x-motemen/ghq@v1.2.1

# kubernetes
- name: kubernetes/kubectl@v1.23.5
- name: kubernetes-sigs/kustomize@kustomize/v4.5.4
- name: kubernetes-sigs/krew@v0.4.3
- name: stern/stern@v1.21.0
