- name: git clone zplug
  git:
    repo: https://github.com/zplug/zplug.git
    dest: ~/.zplug

- name: find dotfiles path
  find:
    paths: ~/.dotfiles/dotfiles
    file_type: any
    hidden: yes
  register: find

- name: symlink dotfiles
  file:
    src: "~/.dotfiles/dotfiles/{{ item.path | regex_replace('^.*/([^/]+)$', '\\1') }}"
    dest: "~/{{ item.path | regex_replace('^.*/([^/]+)$', '\\1') }}"
    state: link
    force: true
  with_items:
    - "{{ find.files }}"

- name: symlink .vim
  file:
    src: ~/.config/nvim
    dest: ~/.vim
    state: link
    force: true

- name: symlink .vimrc
  file:
    src: ~/.config/nvim/init.vim
    dest: ~/.vimrc
    state: link
    force: true

- name: symlink docker completion for zsh
  file:
    src: /Applications/Docker.app/Contents/Resources/etc/docker.zsh-completion
    dest: /usr/local/share/zsh/site-functions/_docker
    state: link
    force: true

- name: symlink docker-machine completion for zsh
  file:
    src: /Applications/Docker.app/Contents/Resources/etc/docker-machine.zsh-completion
    dest: /usr/local/share/zsh/site-functions/_docker-machine
    state: link
    force: true

- name: symlink docker-compose completion for zsh
  file:
    src: /Applications/Docker.app/Contents/Resources/etc/docker-compose.zsh-completion
    dest: /usr/local/share/zsh/site-functions/_docker-compose
    state: link
    force: true
 
