[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
if = 'has("nvim")'
hook_add = 'source ~/.config/nvim/plugins/denite.vim'

[[plugins]]
repo =  'altercation/vim-colors-solarized'
hook_add="""
let g:solarized_contrast="hight"
let g:solarized_italic=0
let g:solarized_termcolors=256
let g:solarized_termtrans=1
"""
