[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = ['mengelbrecht/lightline-bufferline']
hook_add = 'source ~/.config/nvim/plugins/lightline.vim'

[[plugins]]
repo = 'mengelbrecht/lightline-bufferline'

[[plugins]]
repo =  'altercation/vim-colors-solarized'
hook_add = 'source ~/.config/nvim/plugins/solarized.vim'
