apt_repositories:
  - "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
  - "ppa:neovim-ppa/stable"

apt_require_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common

apt_packages:
  - build-essential
  - docker-ce
  - git
  - neovim
  - python-dev
  - python-pip
  - python3-dev
  - python3-pip
  - vim
  - zsh
