name: Check scripts
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
permissions:
  contents: read
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: .chezmoiscripts
          ignore_paths: .chezmoiscripts/windows
  PSSrcriptAnalyzer:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@v1.1
        with:
          path: .chezmoiscripts/windows
          recurse: true
          output: results.sarif
