name: CI

on:
  push:

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: |
        cp -rp $GITHUB_WORKSPACE ~/.dotfiles
        cd ~/.dotfiles
        make install
